# Generated by Django 3.2.19 on 2023-06-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='title',
            field=models.CharField(default='Untitled Thought', max_length=48),
        ),
    ]
