# Generated by Django 3.2.19 on 2023-06-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0003_comment_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='content',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='thought',
            name='title',
            field=models.CharField(default='Untitled Thought', max_length=96),
        ),
    ]
