# Generated by Django 3.2.19 on 2023-07-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0006_auto_20230711_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='title',
            field=models.CharField(max_length=96),
        ),
    ]
